# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:11
from __future__ import unicode_literals

import console.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='templates_file_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('content', console.models.CompressedTextField()),
                ('modify_by', models.CharField(max_length=64)),
                ('modify_time', models.DateTimeField()),
            ],
        ),
    ]
