# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='sever_url_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=64)),
                ('default_path', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='userinfo',
            new_name='user_info',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='companyCode',
            new_name='company_code',
        ),
    ]
